development:
  adapter: postgresql
  encoding: unicode
  database: soloqueue
  pool: 5
  timeout: 5000
  username: vitrue
  password: 


# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000

